<a href="https://colab.research.google.com/github/sandeep92134/The-Data-Visualization-Workshop-by-packt/blob/master/module%201/Activity_1_01_Using_NumPy_to_Compute_the_Mean%2C_Median%2C_Variance%2C_and_Standard_Deviation_of_a_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Activity 1.01: Using NumPy to Compute the Mean, Median, Variance, and Standard Deviation of a Dataset

In this activity, you will consolidate the skills you've acquired in the last exercise and use NumPy to do some very basic mathematical calculations on our `normal_distribution` dataset.   
NumPy has a consistent API, so it should be rather easy to transfer your knowledge of the mean method to median and variance. 

#### Loading the dataset

In [ ]:
# importing the necessary dependencies
import numpy as np

In [ ]:
# loading the Dataset
dataset = np.genfromtxt('normal_distribution.csv', delimiter=',')

In [ ]:
# looking at the first two rows of the dataset
dataset[0:2]

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942]])

---

#### Mean

In [ ]:
# calculate the mean of the third row
np.mean(dataset[2])

100.20466135250001

In [ ]:
# calculate the mean of the last column
np.mean(dataset[:,-1])

100.4404927375

In [ ]:
# calculate the mean of the intersection of the first 3 rows and first 3 columns
np.mean(dataset[0:3, 0:3])

97.87197312333333

---

#### Median

In [ ]:
# calculate the median of the last row
np.median(dataset[-1])

99.18748092

In [ ]:
# calculate the median of the last 3 columns
np.median(dataset[:, -3:])

99.47332349999999

In [ ]:
# calculate the median of each row
np.median(dataset, axis=1)

array([ 98.77910163,  97.17512034,  98.58782879, 100.68449836,
       101.00170737,  97.76908825, 101.85002253, 100.04756697,
       102.24292555,  99.59514997, 100.4955753 ,  99.8860714 ,
        99.00647994,  98.67276177, 102.44376222,  96.61933565,
       104.0968893 , 100.72023043,  98.70877396,  99.75008654,
       104.89344428, 101.00634942,  98.30543801,  99.18748092])

---

#### Variance

In [ ]:
# calculate the variance of each column
np.var(dataset, axis=0)

array([23.64757465, 29.78886109, 20.50542011, 26.03204443, 28.38853175,
       19.09960817, 17.67291174, 16.17923204])

In [ ]:
# calculate the variance of the intersection of the last 2 rows and first 2 columns
np.var(dataset[-2:, :2])

4.674691991769191

The values of the variance might seem a little bit strange at first.   
You can always go back to the topic that gives you a quick statistical overview to recap what you've learned so far.   

> **Note:**   
Just remember, the variance is not the standard deviation.   

Try calculation the standard deviation with NumPy to get a more descriptive value when comparing it to our dataset

In [ ]:
# calculate the standard deviation for the dataset
np.std(dataset)

4.838197554269257